#include "copied_hpp_file/enable_if.hpp"
#include "copied_hpp_file/header.hpp"
#include "copied_hpp_file/is_integral.hpp"
#include "copied_hpp_file/iterator.hpp"
#include "copied_hpp_file/stack.hpp"
#include "copied_hpp_file/vector.hpp"
